new

diff --git a/Jenkins-Pipeline-Code/Jenkinsfile-Frontend b/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
--- a/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
+++ b/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
@@ -4,12 +4,12 @@ pipeline {
         jdk 'jdk'
         nodejs 'nodejs'
     }
-    environment  {
+    environment {
         SCANNER_HOME=tool 'sonar-scanner'
-        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
-        AWS_ECR_REPO_NAME = credentials('ECR_REPO1')
-        AWS_DEFAULT_REGION = 'us-east-1'
-        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
+        GCP_CRED = credentials('gcp')
+        GCP_REGION = 'us-east1'
+        GIT = credentials('GIT')
+        ARTIFACT_REGISTRY_URI = "us-east1-docker.pkg.dev/advance-replica-428411-v0/frontend"
     }
     stages {
         stage('Cleaning Workspace') {
@@ -18,94 +18,96 @@ pipeline {
             }
         }
         stage('Checkout from Git') {
-            steps {
-                git credentialsId: 'GITHUB', url: 'https://github.com/AmanPathak-DevOps/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
-            }
-        }
-        stage('Sonarqube Analysis') {
-            steps {
-                dir('Application-Code/frontend') {
-                    withSonarQubeEnv('sonar-server') {
-                        sh ''' $SCANNER_HOME/bin/sonar-scanner \
-                        -Dsonar.projectName=three-tier-frontend \
-                        -Dsonar.projectKey=three-tier-frontend '''
-                    }
-                }
-            }
-        }
-        stage('Quality Check') {
-            steps {
-                script {
-                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
-                }
-            }
-        }
-        stage('OWASP Dependency-Check Scan') {
-            steps {
-                dir('Application-Code/frontend') {
-                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
-                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
-                }
-            }
-        }
-        stage('Trivy File Scan') {
-            steps {
-                dir('Application-Code/frontend') {
-                    sh 'trivy fs . > trivyfs.txt'
-                }
-            }
-        }
+    steps {
+        git credentialsId: 'GIT', url: 'https://github.com/lokesh2201013/three-tier-app-pipeline.git', branch: 'main'
+    }
+}
         stage("Docker Image Build") {
             steps {
                 script {
                     dir('Application-Code/frontend') {
-                            sh 'docker system prune -f'
-                            sh 'docker container prune -f'
-                            sh 'docker build -t ${AWS_ECR_REPO_NAME} .'
+                        sh 'docker system prune -f'
+                        sh 'docker container prune -f'
+                        // Build the Docker image
+                        sh 'gcloud auth configure-docker us-east1-docker.pkg.dev'
+                        sh 'docker build -t frontend:latest .'
+                        // Tag the Docker image with the desired tag
+                        sh 'docker tag frontend:latest ${ARTIFACT_REGISTRY_URI}/frontend:${BUILD_NUMBER}'
                     }
                 }
             }
         }
-        stage("ECR Image Pushing") {
+        stage("GCR Image Pushing") {
             steps {
                 script {
-                        sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}'
-                        sh 'docker tag ${AWS_ECR_REPO_NAME} ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
-                        sh 'docker push ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
+                    sh 'gcloud auth configure-docker'
+                    // Push the tagged Docker image
+                    sh 'docker push ${ARTIFACT_REGISTRY_URI}/frontend:${BUILD_NUMBER}'
                 }
             }
         }
-        stage("TRIVY Image Scan") {
-            steps {
-                sh 'trivy image ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} > trivyimage.txt' 
+        /* Uncomment the following block if you want to include parallel scanning
+        stage('Parallel Scanning') {
+            parallel {
+                stage('SonarQube Analysis') {
+                    steps {
+                        dir('frontend/Application-Code/frontend') {
+                            withSonarQubeEnv('sonar-server') {
+                                sh ''' $SCANNER_HOME/bin/sonar-scanner \
+                                -Dsonar.projectName=frontend \
+                                -Dsonar.projectKey=frontend '''
+                            }
+                        }
+                    }
+                }
+                stage('TRIVY Image Scan') {
+                    steps {
+                        // Update Trivy command to only show critical and high severity vulnerabilities
+                        sh 'trivy image --severity HIGH,CRITICAL ${ARTIFACT_REGISTRY_URI}/frontend:${BUILD_NUMBER} > trivyimage.txt' 
+                        archiveArtifacts artifacts: 'trivyimage.txt', allowEmptyArchive: true
+                    }
+                }
             }
-        }
-        stage('Checkout Code') {
+        } */
+        /*stage('TRIVY Image Scan') {
             steps {
-                git credentialsId: 'GITHUB', url: 'https://github.com/AmanPathak-DevOps/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
+                // Update Trivy command to only show critical and high severity vulnerabilities
+                sh 'trivy image --severity HIGH,CRITICAL ${ARTIFACT_REGISTRY_URI}/frontend:${BUILD_NUMBER} > trivyimage.txt' 
+                archiveArtifacts artifacts: 'trivyimage.txt', allowEmptyArchive: true
             }
-        }
+        }*/
+        /* stage('Quality Check') {
+            steps {
+                script {
+                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
+                }
+            }
+        } */
         stage('Update Deployment file') {
             environment {
-                GIT_REPO_NAME = "End-to-End-Kubernetes-Three-Tier-DevSecOps-Project"
-                GIT_USER_NAME = "AmanPathak-DevOps"
+                GIT_REPO_NAME = "three-tier-app-pipeline"
+                GIT_USER_NAME = "lokesh2201013"
             }
             steps {
                 dir('Kubernetes-Manifests-file/Frontend') {
-                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                         sh '''
-                            git config user.email "aman07pathak@gmail.com"
-                            git config user.name "AmanPathak-DevOps"
-                            BUILD_NUMBER=${BUILD_NUMBER}
-                            echo $BUILD_NUMBER
-                            imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
-                            echo $imageTag
-                            sed -i "s/${AWS_ECR_REPO_NAME}:${imageTag}/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}/" deployment.yaml
-                            git add deployment.yaml
-                            git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
-                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
+                           set -x  # Enable debugging
+                        git config user.email "lokeshchoraria60369@gmail.com"
+                        git config user.name "lokesh2201013"
+                        BUILD_NUMBER=${BUILD_NUMBER}
+                        echo $BUILD_NUMBER
+                        cat deployment.yaml  # View the content of deployment.yaml for debugging
+                        imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
+                        if [ -z "$imageTag" ]; then
+                            echo "Error: Could not extract image tag from deployment.yaml"
+                            exit 1
+                        fi
+                        echo "Extracted image tag: $imageTag"
+                        sed -i "s|${ARTIFACT_REGISTRY_URI}/frontend:${imageTag}|${ARTIFACT_REGISTRY_URI}/frontend:${BUILD_NUMBER}|" deployment.yaml
+                        git add deployment.yaml
+                        git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
+                        git push https://${GIT}@github.com/lokesh2201013/three-tier-app-pipeline HEAD:main
                         '''
-                    }
                 }
             }
         }
